package com.pojo;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.number
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.miaoshu
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private String miaoshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.number
     *
     * @return the value of goods.number
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.number
     *
     * @param number the value for goods.number
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.miaoshu
     *
     * @return the value of goods.miaoshu
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public String getMiaoshu() {
        return miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.miaoshu
     *
     * @param miaoshu the value for goods.miaoshu
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setMiaoshu(String miaoshu) {
        this.miaoshu = miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img
     *
     * @return the value of goods.img
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img
     *
     * @param img the value for goods.img
     *
     * @mbg.generated Wed Dec 04 15:41:17 CST 2019
     */
    public void setImg(String img) {
        this.img = img;
    }

	@Override
	public String toString() {
		return "Goods [id=" + id + ", name=" + name + ", price=" + price + ", number=" + number + ", miaoshu=" + miaoshu
				+ ", img=" + img + "]";
	}
    
}